repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.257
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest -v tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
