# Build Stage
FROM node:18-alpine AS build
WORKDIR /
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve the static files with Nginx
FROM nginx:alpine
COPY --from=build /src/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
